# Generated by Django 5.1.3 on 2024-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.URLField()),
                ('solution', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('obtain_result', models.IntegerField()),
            ],
        ),
    ]
