# Generated by Django 5.1.3 on 2024-11-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_obtain_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='solution',
            new_name='actual_solution',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='obtain_result',
            new_name='user_solution',
        ),
    ]
